name: Test and release

# Fires on all incoming commits
on:
  pull_request:
  push:

jobs:

  # Lint
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install tox -U pip
      - name: Lint
        run: tox -e package

  # Create a new semantic release
  # Only runs on the original repo, not forks
  release:
    if: github.repository_owner == 'stephenmcd'
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/setup-node@v2
        with:
          node-version: '14' # https://github.com/cycjimmy/semantic-release-action/issues/79#issuecomment-955463633
      - uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/exec@5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
